tokens/design-token.json

feat: add new tokens

---

tokens/design-token.json

feat: add finhub token

---

figma-icon-plugin/.gitignore
figma-icon-plugin/manifest.json
figma-icon-plugin/package-lock.json
figma-icon-plugin/package.json
figma-icon-plugin/src/plugin/code.ts
figma-icon-plugin/src/ui/components/App.tsx
figma-icon-plugin/src/ui/components/CalloutBox.tsx
figma-icon-plugin/src/ui/components/GithubDataProvider.tsx
figma-icon-plugin/src/ui/components/Publish.tsx
figma-icon-plugin/src/ui/components/Setting.tsx
figma-icon-plugin/src/ui/style/global.css
figma-icon-plugin/src/ui/type/type.ts
figma-icon-plugin/src/ui/ui.html
figma-icon-plugin/src/ui/ui.tsx
figma-icon-plugin/src/utils/githubApi.ts
figma-icon-plugin/src/utils/util.ts
figma-icon-plugin/tsconfig.json
figma-icon-plugin/webpack.config.js

feat: add figma-icon-plugin

---

packages/fotcamp-components/src/components/Funnel/Funnel.stories.tsx
packages/fotcamp-components/src/components/Funnel/Funnel.tsx
packages/fotcamp-components/src/components/Funnel/Funnel.type.ts
packages/fotcamp-components/src/components/Funnel/index.ts
packages/fotcamp-components/src/components/Funnel/useFunnel.tsx
packages/fotcamp-components/src/components/Funnel/useQueryParam.ts
packages/fotcamp-components/src/hooks/useRouter.ts
packages/fotcamp-components/src/index.ts
packages/fotcamp-components/src/router/router.type.ts
packages/fotcamp-components/src/router/windowRouter.ts

사용 예시는 [Storybook](https://github.com/fotcamp/fotcamp-design-system/blob/35667d5373ad3438539d710fbcb19843c63176c5/packages/fotcamp-components/src/components/Funnel/Funnel.stories.tsx)에 명세하였습니다.
URL query기반의 Funnel component & useFunnel hook 입니다.
```ts
export const useFunnel = <Steps extends NonEmptyArray<string>>(
steps: Steps,
options?: {
stepQueryKey?: string;
initialStep?: Steps[number];
}
) => {
const router = useRouter();
const stepQueryKey = options?.stepQueryKey ?? DEFAULT_STEP_QUERY_KEY;
if (steps.length === 0) {
throw new Error("steps가 비어있습니다.");
}
const FunnelComponent = useMemo(
() =>
Object.assign(
function RouteFunnel(props: RouteFunnelProps<Steps>) {
const step =
useQueryParam<Steps[number]>(stepQueryKey) ?? options?.initialStep;
if (!step) {
throw new Error(
`표시할 스텝을 …
```

Funnel component(using Safe Router)

---

packages/fotcamp-components/src/index.ts
packages/fotcamp-components/src/shared/storage/LocalStorage.ts
packages/fotcamp-components/src/shared/storage/MemoryStorage.ts
packages/fotcamp-components/src/shared/storage/SessionStorage.ts
packages/fotcamp-components/src/shared/storage/index.ts
packages/fotcamp-components/src/shared/storage/storage.type.ts
packages/fotcamp-components/src/utils/generateRandomKey.ts

localStorage, sessionStorage의 공통의 구현체를 만들고 사용할 수 없는 상황에도 대응할 수 있도록 하는 것을 목표로 하였습니다.
```ts
export interface SafeStorage {
get(key: string): string | null; // key 조회
set(key: string, value: string): void; // key에 값 저장
remove(key: string): void; // key 삭제
clear(): void; // storage 삭제
has(key: string): boolean; // key 존재 여부
}
```
LocalStorage, SessionStorage를 사용할 수 없을 때 메모리에서 대응할 수 있도록 하였습니다.
Map 자료구조를 사용하여 조회 및 삭제 성능을 고려하고 storage interface와 유사한 이점을 활용하였습니다.
```ts
export class MemoryStorage implements SafeStorage {
private map = new Map<string, string>();
has(key: string): boolean {
return this.map.get(key) !== null;
}
get(key: string) {
return this.map.get(key) || null;
}
set(key: string, value: string) {
this.map.set(key, value);
}
remove(key: string) {
this.map.delete(key);
}
clear() { …
```

Safe Storage(LocalStorage, SessionStorage, MemoryStorage)

---

packages/fotcamp-components/package-lock.json
packages/fotcamp-components/package.json
packages/fotcamp-components/src/components/Toggle/Toggle.stories.tsx
packages/fotcamp-components/src/components/Toggle/Toggle.tsx
packages/fotcamp-components/src/components/Toggle/Toggle.type.ts
packages/fotcamp-components/src/components/Toggle/index.ts
packages/fotcamp-components/src/index.ts

- Toggle 컴포넌트 추가
- @radix-ui/react-toggle 라이브러리 추가

[@fotcamp/components] 토글 컴포넌트 추가

---

packages/fotcamp-components/package-lock.json
packages/fotcamp-components/package.json
packages/fotcamp-components/src/components/Checkbox/Checkbox.stories.tsx
packages/fotcamp-components/src/components/Checkbox/Checkbox.tsx
packages/fotcamp-components/src/components/Checkbox/Checkbox.type.ts
packages/fotcamp-components/src/components/Checkbox/index.ts
packages/fotcamp-components/src/index.ts

- Checkbox 컴포넌트 추가
- @radix-ui/react-checkbox 라이브러리 추가

[@fotcamp/components] 체크박스 컴포넌트 추가

---

packages/fotcamp-components/package-lock.json
packages/fotcamp-components/package.json
packages/fotcamp-components/src/components/RadioGroup/RadioGroup.stories.tsx
packages/fotcamp-components/src/components/RadioGroup/RadioGroup.tsx
packages/fotcamp-components/src/components/RadioGroup/RadioGroup.type.ts
packages/fotcamp-components/src/components/RadioGroup/index.ts
packages/fotcamp-components/src/index.ts

- RadioGroup 컴포넌트 추가
- @radix-ui/react-radio-group 라이브러리 추가
- Indicator 협의가 필요합니다.

[@fotcamp/components] 라디오그룹 컴포넌트 추가

---

packages/fotcamp-components/package-lock.json
packages/fotcamp-components/package.json
packages/fotcamp-components/src/components/Select/Select.scss
packages/fotcamp-components/src/components/Select/Select.stories.tsx
packages/fotcamp-components/src/components/Select/Select.tsx
packages/fotcamp-components/src/components/Select/Select.type.ts
packages/fotcamp-components/src/components/Select/index.ts
packages/fotcamp-components/src/index.ts
packages/fotcamp-components/src/style/index.scss

- Select 컴포넌트 추가
- @radix-ui/react-select 라이브러리 추가

[@fotcamp/components] Select 컴포넌트 추가

---

figma/design-token.json

24.11.20 token generation

---

packages/figma-token/figma/design-token.json

rem to px 변경

---

packages/figma-token/src/build.js

close #53 
https://dgf7bkcblr65n.cloudfront.net/design-token/other-pc.css

[@fotcamp/figma-token] 폰트 추가 

---

packages/fotcamp-components/src/components/Accordian/Accordion.stories.tsx
packages/fotcamp-components/src/components/Accordian/Accordion.tsx
packages/fotcamp-components/src/components/Accordian/Accordion.type.ts
packages/fotcamp-components/src/components/BottomSheet/BottomSheet.stories.tsx
packages/fotcamp-components/src/components/BottomSheet/BottomSheet.tsx
packages/fotcamp-components/src/components/BottomSheet/BottomSheet.type.ts
packages/fotcamp-components/src/components/Dialog/Dialog.stories.tsx
packages/fotcamp-components/src/components/Dialog/Dialog.tsx
packages/fotcamp-components/src/components/Dialog/Dialog.type.ts
packages/fotcamp-components/src/components/Popover/Popover.stories.tsx
packages/fotcamp-components/src/components/Popover/Popover.tsx
packages/fotcamp-components/src/components/Popover/Popover.type.ts
packages/fotcamp-components/src/components/Toast/Toast.scss
packages/fotcamp-components/src/components/Toast/Toast.stories.tsx
packages/fotcamp-components/src/components/Toast/Toast.tsx
packages/fotcamp-components/src/components/Toast/Toast.type.ts
packages/fotcamp-components/src/components/Toast/ToastProvider.tsx
packages/fotcamp-components/src/components/Toast/useToastStack.ts

- data-fotcamp-component 적용(data* 속성 selector)
- headless radix 기반 유지하고 wrapping
- Toast options 수정, Toast Provider 기본 옵션 받을 수 있게 변경

components convention 적용

---

.github/workflows/storybook-CD.yml

- github page 추가 및 stroybook cd 추가

chore: add storybook deploy github action

---

.github/workflows/chromatic-CD.yml

chore: chage chromatic cd on branch to main

---

packages/fotcamp-components/src/components/Accordian/Accordion.stories.tsx

test: cd test

---

packages/moeum-components/src/components/Checkbox/Checkbox.stories.tsx
packages/moeum-components/src/components/RadioGroup/RadioGroup.stories.tsx
packages/moeum-components/src/components/Select/Select.scss
packages/moeum-components/src/components/TextField/TextArea/TextArea.scss
packages/moeum-components/src/components/TextField/TextField.scss

close #83 
- https://github.com/team-moeum/moeum-design-system/tree/main/packages/figma-token
- https://dgf7bkcblr65n.cloudfront.net/design-token/color-light.css
- https://dgf7bkcblr65n.cloudfront.net/design-token/other-pc.css
컴포넌트에 신규 토큰을 적용하는 템플릿을 개발하였습니다.

[@moeum/components] 컴포넌트 토큰 적용

---

.github/workflows/chromatic-CD.yml

github action PR slack 알림 메세지 추가
close #94 
- workflow에 slack message 추가했습니다
- 성공 시 storybook url, pr link
- 실패 시 pr link
- mention 기능 추가에 대한 논의를 제안드립니다. 현재는 채널에 공통 알림으로 해도 문제없다는 판단을 하였습니다.
예)
**AS-IS**
❌ **Storybook 배포에 실패했습니다!** 
🔍 PR: ${{ github.event.pull_request.html_url }}
🚨 확인이 필요합니다.
**TO-BE**
❌ **Storybook 배포에 실패했습니다!** 
🔍 PR: ${{ github.event.pull_request.html_url }}
🚨 확인이 필요합니다.
@widse  @seungdeok

[feat/#94] [@moeum/components] github action PR slack 알림 메세지 추가

---

packages/figma-token/figma/design-token.json

@seungdeok 
https://github.com/team-moeum/moeum-design-system/pull/103#issuecomment-2629341133
위 이슈 관련 디자인 토큰 업데이트 하였습니다!
**disabled 버튼 텍스트 스타일 토큰/hex값**
seed-ui-color-text-disabled / #C6CCD1 입니다~!

디자인 토큰 업데이트 드립니다!

---

packages/figma-token/figma/design-token.json

디자인시스템-토큰 재배포 합니다(px변환추가)

---

packages/figma-componentgen-plugin/manifest.json
packages/figma-componentgen-plugin/package.json
packages/figma-componentgen-plugin/src/Main.tsx
packages/figma-componentgen-plugin/src/code.ts
packages/figma-componentgen-plugin/src/ui.html
packages/figma-componentgen-plugin/src/ui.tsx
packages/figma-componentgen-plugin/src/utils/copyToClipboard.ts
packages/figma-componentgen-plugin/src/utils/figmaToJson.ts
packages/figma-componentgen-plugin/src/utils/jsonToCompoenent.ts
packages/figma-componentgen-plugin/src/utils/notify.ts
packages/figma-componentgen-plugin/tsconfig.json
packages/figma-componentgen-plugin/webpack.config.js
pnpm-lock.yaml

[Feat/#117] design system plugin 

---

README.md
packages/figma-componentgen-plugin/README.md
packages/figma-token/README.md
packages/moeum-icons/README.md

사용자가 패키지를 원활히 사용할 수 있도록 가이드를 작성하고자 합니다.

docs: Update readme

---

packages/moeum-icons/README.md

Icon Plugin 사용가이드를 작성하였습니다.
close #132

[@moeum/icons] Icon Plugin 사용가이드

---

packages/moeum-icons/package.json

package.json repo 주소와 keyword를 수정합니다.
closes #123

[Feat/#123] package.json repo 정보 변경
